### ISSUE TITLE
optional nuts in mint info endpoint

### ISSUE THREAD

**Issue by elnosh** [ngutech21/moksha#268]
should the `pub struct Nuts` in https://github.com/ngutech21/moksha/blob/master/moksha-core/src/primitives.rs#L339 have the fields from `nut7` and forward (the optional nuts) be an Option?

it seems that if the wallet tries to call the `/v1/info` endpoint and the mint doesn't include the optional nuts in the response, then the client will panic when parsing the json response.

**Comment by ngutech21** [comment]
I think the spec is not 100 % clear on that topic. NUT-06 doesn't mention the nuts in the info endpoint being optional, but I think you are right. Making them optional would be better. This is what I did for NUT-17 and NUT-18. To check the compatibility with the python reference implementation I have added an integrationtest: https://github.com/ngutech21/moksha/blob/master/integrationtests/tests/tests_nutshell_compatibility.rs

Which mint are you using for testing?

**Comment by elnosh** [comment]
> I think the spec is not 100 % clear on that topic.

yeah it's not very clear if the mints need to announce all of them. I'm thinking mints shouldn't need to announce optional nuts in their info endpoint, omission can be interpreted as not supported I guess.

> Which mint are you using for testing?

I was testing with gonuts. I'm not including the optional nuts in the info endpoint and was getting the panic with the wallet. I should probably just add the `{"supported": false}` to the optional ones that are not supported yet. But still thought the wallet could just ignore it and continue as if the mint only supports the mandatory ones

**Comment by ngutech21** [comment]
@elnosh 
I think moving forward it makes more sense to be less strict, so I changed all Nuts > 6 to Option<T>. Thanks for the feedback.
