### ISSUE TITLE
NUT-06 info endpoint version serialization wrong

### ISSUE THREAD

**Issue by jblachly** [ngutech21/moksha#319]
Per NUT-06

> version is the implementation name and the version of the software running on this mint separated with a slash "/",

The latest Moksha built from source serializes:
```
"version":"0.2.1-"
```

This could break a downstream client that tries to parse the field into two parts (program/version) by slash

# References
 - https://github.com/cashubtc/nuts/blob/main/06.md

**Comment by ngutech21** [comment]
Nice catch. I wasn't aware of the constraints inside the version-string. This should be easy to fix.
